# Generated by Django 4.0.3 on 2022-04-01 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('profile_pic', models.ImageField(upload_to='profiles')),
                ('start_date', models.DateField(default=datetime.datetime(2022, 4, 1, 10, 40, 32, 621935))),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
