# Generated by Django 4.0.3 on 2022-05-03 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_alter_myuser_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 3, 12, 12, 36, 504680)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(max_length=50),
        ),
    ]
