# Generated by Django 4.0.3 on 2022-05-18 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_product_id_alter_myuser_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 11, 14, 11, 688191)),
        ),
    ]
